#!/usr/bin/env bash

# Usage:
# $ safe rm ./*
# > Are you sure you want to 'rm ./*'? [y/n]
# $ y
# $ rm ./*

args_arr=("$@")
echo "Are you sure you want to '"${args_arr[@]}"'? [y/n]"
read is_sure
case $is_sure in
    [Yy]*)
        "${args_arr[@]}"
    ;;
    *)
        echo "Ok, moving on. They say, better to be safe than sorry."
    ;;
esac

