#!/usr/bin/env bash

# Usage:
# $ safe rm *
# > rm LICENSE README.md safe
# Are you sure? y|n n

echo '> '$@
read -p 'Are you sure? y|n ' -n1
echo ''
case $REPLY in y|Y)
    echo 'Alright.'
    "$@"
    exit
    ;;
esac
echo 'Ok, moving on. They say, better to be safe than sorry.'

